version: '3'

services:
  payments:
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/gem
      - ..:/local
      - bundle-cache:/usr/local/bundle:delegated
    env_file: .env

volumes:
  bundle-cache:
