version: '3'

services:
  venme:
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/gem
      - ..:/local
      - bundle-cache:/usr/local/bundle:delegated

volumes:
  bundle-cache:
